### ISSUE TITLE
Padding requirement

### ISSUE THREAD

**Issue by irothschild** [keenlabs/KeenClient-Python#100]
Now that Padding.py is included in this module to support Python 3, I think it should be removed from the requirements.txt.

PR https://github.com/keenlabs/KeenClient-Python/pull/101

**Comment by irothschild** [comment]
Can someone please merge this pull request and release a new version that can pip install on Python 3 without giving errors when running compileall? Thanks.

**Comment by dkador** [comment]
This should be all fixed now.
