### ISSUE TITLE
De-emphasize master key usage in the README

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-Python#106]
The master key is the most sensitive API Key available in Keen, and I would like to make it clear in the docs that it is not required for most cases.

I'd suggest removing all references to the master key in the README, aside from:
- The one in the "Usage" section, near the top. Leave that reference, but add a comment `# not required in most situations`
- It can remain in sections of the docs that actually require the master key (currently, there are no sections that require it)

**Comment by masojus** [comment]
Fixed by Pull Request #122
