### ISSUE TITLE
Add support for Datasets

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-Python#108]

**Comment by SteadBytes** [comment]
I'd like to take this up - is that ok? I'm thinking of a similar implementation to the [saved queries](https://github.com/keenlabs/KeenClient-Python/blob/45ad5a2523f42f1d3f0f8cb0ece8dd080052149d/keen/saved_queries.py#L15) 😄

**Comment by BlackVegetable** [comment]
I don't think anyone would stop you! :) Thanks!

**Comment by SteadBytes** [comment]
Great! Thank you

**Comment by masojus** [comment]
Closed by PR #150
