### ISSUE TITLE
Warn users if they are using the master key when they shouldn't

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-Python#112]
Right now if the user puts in a master key, but not the correct (read or write) key, we throw a generic error. We should specifically check to see if a master key is available if read/write are unavailable, and throw a different error if so. I **do not want** to fall back on the master key, but I *do* want to explicitly inform the user that the master key shouldn't be used for lower privilege endpoints.

**Comment by masojus** [comment]
Fixed by Pull Request #121
