### ISSUE TITLE
Deprecate Python 3.2 Support

### ISSUE THREAD

**Issue by masojus** [keenlabs/KeenClient-Python#129]
Problems described in Issue #126 are a result of a larger issue, as demonstrated in the links mentioned by @baumatron in that bug. Namely, that pip and [setuptools](https://github.com/pypa/setuptools/issues/864) dropped support for Python 3.2. Should we follow suit?

We could just drop 3.2 from the Travis config and remove mentions of it in the README and setup.py classifiers, if that's the case.

**Comment by craigds** [comment]
Not sure about progress on this, but IME it's very rare for libraries to support python 3.2, and I doubt you've got [m]any users still using it. Most apps switching to python 3.x went directly to 3.3+ because of the reintroduction of `u''` literals.

Looks like python 3.2 support is the reason this library is pinning our `requests` version to `<2.11` so we'd appreciate that being dropped so we can upgrade it.

**Comment by dkador** [comment]
@masojus - I'd be fine with dropping support for 3.2 going forward.

**Comment by masojus** [comment]
We can shuffle this up a bit in priority to hopefully ameliorate the dependency issues @craigds is seeing.

**Comment by masojus** [comment]
@craigds is the issue that the `requirements.txt` demands `requests>=2.5,<2.11.0`? To rectify that will require more testing.

**Comment by masojus** [comment]
We could look at what it means to depend upon `2.18.x` or something instead, but either way Python 3.2 testing can go away.

**Comment by craigds** [comment]
yep that's the issue. I came across this through the git blame, in which that line was added specifically to keep Python 3.2 compatibility: https://github.com/keenlabs/KeenClient-Python/commit/5706ab31e0deac093c7ce0512cebaef2f9f193e2

**Comment by BlackVegetable** [comment]
This is being addressed in version 0.5.0 #132

**Comment by hugovk** [comment]
Here's the pip installs for keen from PyPI for the last month:
```
$ pypinfo --percent --pip keen pyversion
python_version percent download_count
-------------- ------- --------------
2.7              63.0%          4,135
3.4              18.5%          1,213
3.6              15.8%          1,039
3.5               2.7%            178
3.7               0.0%              2

```

How about dropping Python 2.6 as well? It's been EOL since 2013 and pip has already deprecated support for it and will drop it in the next release.

And 3.3 also went EOL last month, perhaps dropping that too?

**Comment by tbarn** [comment]
Also based on pip data itself [here for 2.6](https://github.com/pypa/pip/issues/3955) and [here for 3.3](https://github.com/pypa/pip/issues/3796), I'm +1 on dropping support of both. 

From the pip data, 3.3 is used even less than 2.6.

**Comment by BlackVegetable** [comment]
Ok. I'm also deprecating 2.6 and 3.3 with the same PR. This thing is getting pretty unwieldy. I'm glad it is being merged today at last.
