### ISSUE TITLE
Breakout Changelog, Create Github Templates

### ISSUE THREAD

**Issue by hydrosquall** [keenlabs/KeenClient-Python#137]
These changes aren't essential but would shorten the core `README.md`. The Templates would increase the odds that new Issues and PRs filed adhere to a format that the development team would find more useful, potentially saving time and energy for everyone involved in the process.

- Breakout a new `CHANGELOG.md` from the `README.md`
- Add a basic `ISSUE_TEMPLATE` and `PULL_REQUEST_TEMPLATE` based on the existing contributions and common practices in the open source community

If these changes sound useful for the project, please let me know in this thread, and I'd be happy to make them.

**Comment by tbarn** [comment]
Hey @hydrosquall! 

I'd be happy to make this work part of Hacktoberfest. Also, including a link to the changelog in the readme would be nice. 

Issue and pull requests templates have been on my list of things I'd like to have. If you want to try your hand at one (maybe similar to the JavaScript SDKs one), I'd be happy to collaborate with you on it.

**Comment by hydrosquall** [comment]
@tbarn - sounds great! I'll put something together and push it up shortly.
