### ISSUE TITLE
Loosen dependencies requirement

### ISSUE THREAD

**Issue by arnaudlimbourg** [keenlabs/KeenClient-Python#148]
Hello,

Using ``pipenv`` ton install this client there is a versioning issue regarding ``six``.

Currently, ``requirements.txt`` specifies ``six ~=1.10.0`` which fails if 1.11.0 is installed. Usually six requirement is a minimum version but not as strict.

Could you loosen it to ``>=1.10``?

**Comment by masojus** [comment]
Both #147 and #149 aim to fix this. For `six` I think we could go with `~=1.10` which would pick up any `1.*.*` >= 1.10.0--that should work whether your have/need 1.10 or 1.11 in your environment.

**Comment by ChristopherHammond13** [comment]
Bump: is this issue still being looked at? It's a simple fix but it would be great to have it upstream to remove our `pip install` warnings that we still have in production. Thanks so much!

**Comment by arnaudlimbourg** [comment]
I ended forking it for as it pipenv would not work otherwise :)

**Comment by masojus** [comment]
This is fixed with PR# 151
