### ISSUE TITLE
Allow setting custom serializers

### ISSUE THREAD

**Issue by gtaylor** [keenlabs/KeenClient-Python#26]
We've got some output from DRF in dict form that has some datetime/date objects in it. DRF has a JSONRenderer class with some custom handlers for both of these, which is super handy. Keen's client, however, doesn't (that I can see).

This means we end up JSON encoding the DRF data structures, then json.loads() to get them all back in string form, then handing that off to Keen to serialize yet again. Obviously not ideal.

I'd suggest allowing the passing of an encoder class in the Client's constructor, here:

https://github.com/keenlabs/KeenClient-Python/blob/master/keen/client.py#L44

Another possibility would be to allow passing in a custom event class instead, which I could then override and set my own serializer on.

I may be able to submit a pull request for this, so let me know how you'd like to proceed.

**Comment by josephwegner** [comment]
Gonna close this, as it has been stale for awhile. If @gtaylor or other issues are having this issue, please respond here and we can reopen.
