### ISSUE TITLE
Buffering and child process for sending to keen

### ISSUE THREAD

**Issue by deontologician** [keenlabs/KeenClient-Python#4]
Right now, a new connection to keen.io is made on every add_event call. This can get expensive when sending on each completed web-request for example. I'm not sure if this can be accomplished entirely with persistence strategies, but it would be nice to use a second process to handle the io, and the main process (the one calling keen.add_event) just puts events into a queue, so that it isn't blocking on every send.  This pattern is used a lot by logging libraries (for instance [logentries](https://github.com/logentries/le_python/), though they use a thread instead of a process)

**Comment by josephwegner** [comment]
Closing, stale ticket. If you're still having issues, feel free to let us know and we can reopen.
