### ISSUE TITLE
import error urllib3 and persistence_strategies

### ISSUE THREAD

**Issue by citynorman** [keenlabs/KeenClient-Python#50]
Hello boys&girls,

trying to use the python API but stuck at the import stage. When I run "import keen", get below errors. Any help would be great! Thanks!

Did easy_install keen or pip install keen
Python 2.7.8
Ubuntu 14.10 / Ubuntu 14.04.1 LTS

>>> import keen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/keen/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/keen/client.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/keen/api.py", line 8, in <module>
ImportError: No module named packages.urllib3.poolmanager
>>> from keen.client import KeenClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/keen/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/keen/client.py", line 5, in <module>
ImportError: cannot import name persistence_strategies

**Comment by stroud109** [comment]
Hey @citynorman, sorry about the error :( Any chance you could tell me what version of the `requests` lib you're running?

**Comment by citynorman** [comment]
No probs, hope it will make your awesome service better for everyone!

Using requests==2.2.1, full pip freeze below.

apt-xapian-index==0.45
Babel==1.3
blinker==1.3
chardet==2.0.1
Cheetah==2.4.4
cloud-init==0.7.5
colorama==0.2.5
configobj==4.7.2
coverage==4.0a5
decorator==3.4.0
Flask==0.10.1
flask-appconfig==0.9.1
Flask-Babel==0.9
Flask-Bootstrap==3.3.0.1
Flask-Login==0.2.11
Flask-Mail==0.9.1
Flask-OpenID==1.2.4
Flask-SQLAlchemy==2.0
Flask-WhooshAlchemy==0.56
Flask-WTF==0.11
flipflop==1.0
guess-language==0.2
gunicorn==19.3.0
html5lib==0.999
itsdangerous==0.24
Jinja2==2.7.3
jsonpatch==1.3
jsonpointer==1.0
keen==0.3.9
Landscape-Client==14.1
MarkupSafe==0.23
meld3==0.6.10
MySQL-python==1.2.5
numpy==1.9.2
oauth==1.0.1
Padding==0.4
PAM==0.4.2
pandas==0.15.2
pbr==0.10.8
prettytable==0.7.2
pycrypto==2.6.1
pyOpenSSL==0.13
pyserial==2.6
python-apt==0.9.3.5
python-dateutil==2.4.1
python-debian===0.1.21-nmu2ubuntu2
python-openid==2.2.5
pytz==2014.10
PyYAML==3.10
requests==2.2.1
sendgrid==1.3.0
six==1.9.0
smtpapi==0.2.0
speaklater==1.3
SQLAlchemy==0.9.9
sqlalchemy-migrate==0.9.5
sqlparse==0.1.14
ssh-import-id==3.21
supervisor==3.0b2
Tempita==0.5.3.dev0
Twisted-Core==13.2.0
urllib3==1.7.1
Werkzeug==0.10.1
Whoosh==2.6.0
WTForms==2.0.2
zope.interface==4.0.5

On Mon, Mar 16, 2015 at 9:06 PM, Stephanie Stroud <notifications@github.com>
wrote:

> Hey @citynorman <https://github.com/citynorman>, sorry about the error :(
> Any chance you could tell me what version of the requests lib you're
> running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keenlabs/KeenClient-Python/issues/50#issuecomment-82015337>
> .
>



-- 
________________________
Norman Niemer
citynorman@googlemail.com
*+1 (917) 436-0963*

**Comment by stroud109** [comment]
Hm, seems like `pip install keen` doesn't automatically grab the latest version of requirements. I'll work on changing that. 

Meanwhile, if you run `pip install requests==2.5.1` do you still see the error?

**Comment by citynorman** [comment]
yay it works now!

On Mon, Mar 16, 2015 at 9:32 PM, Stephanie Stroud <notifications@github.com>
wrote:

> Hm, seems like pip install keen doesn't automatically grab the latest
> version of requirements. I'll work on changing that.
>
> Meanwhile, if you run pip install requests==2.5.1 do you still see the
> error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keenlabs/KeenClient-Python/issues/50#issuecomment-82021449>
> .
>



-- 
________________________
Norman Niemer
citynorman@googlemail.com
*+1 (917) 436-0963*

**Comment by stroud109** [comment]
Woohoo! Glad to hear it :smile: Thanks so much for reporting. 

I'll close this ticket when we fix the setup.py issue.

**Comment by stroud109** [comment]
Fixed this issue in 0.3.11
