### ISSUE TITLE
Unpin Requests Version in requirements

### ISSUE THREAD

**Issue by kevinastone** [keenlabs/KeenClient-Python#54]
Trying to use keen in a project that already requires certain versions of `requests` (`>=2.5.2` in my case).  Pinning to an exact version of requests creates conflicts.  Please only constrain to a minimum version based on the functionality used rather than pinning the exact version.

I'd expect a library to be more flexible in which versions of requests it supports.

**Comment by stroud109** [comment]
Good point. PRs happily accepted if you need this to change this weekend. Otherwise, I'll add this to the TODO list for upcoming changes.
