### ISSUE TITLE
pip install fails on RPi

### ISSUE THREAD

**Issue by kgf** [keenlabs/KeenClient-Python#58]
Attempting to pip install on Raspbian for IoT.

python --version
Python 2.7.3

pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

Here is the output
pip install keen
Downloading/unpacking keen
  Downloading keen-0.3.12.tar.gz
  Running setup.py egg_info for package keen
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/keen/setup.py", line 15, in <module>
        install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())
    AttributeError: 'module' object has no attribute 'PipSession'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/keen/setup.py", line 15, in <module>

    install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())

AttributeError: 'module' object has no attribute 'PipSession'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/keen
Storing complete log in /home/pi/.pip/pip.log

**Comment by kgf** [comment]
Here is the data from ~/.pip/pip.log

pi@sbc-pi-01 ~ $ cat ~/.pip/pip.log 
Downloading/unpacking keen

  Getting page http://pypi.python.org/simple/keen
  URLs to search for versions for keen:
  * http://pypi.python.org/simple/keen/
  Getting page http://pypi.python.org/simple/keen/
  Analyzing links from page https://pypi.python.org/simple/keen/
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.2.tar.gz#md5=a9dd8ce4da5ab3df75951ba3aac7113e (from https://pypi.python.org/simple/keen/), version: 0.1.2
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.3.tar.gz#md5=9d63159dc6b06453f69340cb39be8c57 (from https://pypi.python.org/simple/keen/), version: 0.1.3
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.4.tar.gz#md5=d88d83b188ccea130c3e691917f62b81 (from https://pypi.python.org/simple/keen/), version: 0.1.4
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.5.tar.gz#md5=8610b720682d60eb1032ef8289854729 (from https://pypi.python.org/simple/keen/), version: 0.1.5
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.6.tar.gz#md5=13169299d2f4089d78d6050e79895318 (from https://pypi.python.org/simple/keen/), version: 0.1.6
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.7.tar.gz#md5=fa7cd18da6749557b990dfd3b76dbb66 (from https://pypi.python.org/simple/keen/), version: 0.1.7
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.8.tar.gz#md5=d1715cb810495c640d02d30bcfb9c501 (from https://pypi.python.org/simple/keen/), version: 0.1.8
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.1.9.tar.gz#md5=61b0088171a227588aa0074ba92b9675 (from https://pypi.python.org/simple/keen/), version: 0.1.9
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.2.0.tar.gz#md5=560d3c1ba4031130af3193c46267f8a6 (from https://pypi.python.org/simple/keen/), version: 0.2.0
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.2.1.tar.gz#md5=a377cb645dd7bbf089375b6d0d6410b7 (from https://pypi.python.org/simple/keen/), version: 0.2.1
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.2.2.tar.gz#md5=50df37e42d03d0b0045fac682d3b9eb6 (from https://pypi.python.org/simple/keen/), version: 0.2.2
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.2.3.tar.gz#md5=130943f2a6f15d1aecc244403ea4ae7c (from https://pypi.python.org/simple/keen/), version: 0.2.3
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.0.tar.gz#md5=f598dae78c8ca25f1544bacf8f54b670 (from https://pypi.python.org/simple/keen/), version: 0.3.0
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.1.tar.gz#md5=93187e77bfa7ca95fea35999e5db52df (from https://pypi.python.org/simple/keen/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.10.tar.gz#md5=2453c42ae7fc1e2d0462f2b4e66e091a (from https://pypi.python.org/simple/keen/), version: 0.3.10
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.11.tar.gz#md5=a43d335d4dfad43a8759306dc69721af (from https://pypi.python.org/simple/keen/), version: 0.3.11
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.12.tar.gz#md5=aa1f25e6b4f6dd36f8d41f0f62bdfb99 (from https://pypi.python.org/simple/keen/), version: 0.3.12
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.2.tar.gz#md5=55305069b39481f4750bc4fd70977249 (from https://pypi.python.org/simple/keen/), version: 0.3.2
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.3.tar.gz#md5=d6aa21078237ffcb36eeb4ef080ea5c7 (from https://pypi.python.org/simple/keen/), version: 0.3.3
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.4.tar.gz#md5=8d43e05802f95986ec657d919bb005e5 (from https://pypi.python.org/simple/keen/), version: 0.3.4
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.5.tar.gz#md5=136081356d65e9ce61bd452ef3b1f137 (from https://pypi.python.org/simple/keen/), version: 0.3.5
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.6.tar.gz#md5=1f59bfd0a0c948bd0e024a3bf9c91f01 (from https://pypi.python.org/simple/keen/), version: 0.3.6
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.7.tar.gz#md5=9984f9bf56430cdc77f13f81614776f1 (from https://pypi.python.org/simple/keen/), version: 0.3.7
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.8.tar.gz#md5=5098f8170789a2539122aca21b90d002 (from https://pypi.python.org/simple/keen/), version: 0.3.8
    Found link https://pypi.python.org/packages/source/k/keen/keen-0.3.9.tar.gz#md5=8f477b958e0f5c0966c407c5f4ddf654 (from https://pypi.python.org/simple/keen/), version: 0.3.9
  Using version 0.3.12 (newest of versions: 0.3.12, 0.3.11, 0.3.10, 0.3.9, 0.3.8, 0.3.7, 0.3.6, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2)
  Downloading keen-0.3.12.tar.gz

  Downloading from URL https://pypi.python.org/packages/source/k/keen/keen-0.3.12.tar.gz#md5=aa1f25e6b4f6dd36f8d41f0f62bdfb99 (from https://pypi.python.org/simple/keen/)
  Running setup.py egg_info for package keen

    Traceback (most recent call last):

      File "<string>", line 14, in <module>

      File "/home/pi/build/keen/setup.py", line 15, in <module>

        install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())

    AttributeError: 'module' object has no attribute 'PipSession'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/keen/setup.py", line 15, in <module>

    install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())

AttributeError: 'module' object has no attribute 'PipSession'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /home/pi/build/keen

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/pi/build/keen

**Comment by stroud109** [comment]
Hey @kgf, sorry you're experiencing this issue. Any chance you could update your version of `pip` and check if you still experience problems installing Keen? (Looks like pip 1.1 is from 2012 and doesn't support the "session" kwarg for [parse_requirements](https://github.com/pypa/pip/blob/1.1/pip/req.py#L1238).) Also, what version of Raspbian are you running? Thanks so much!

**Comment by stroud109** [comment]
Updated in #61
