### ISSUE TITLE
pycrypto version

### ISSUE THREAD

**Issue by justmobilize** [keenlabs/KeenClient-Python#64]
Currently you are requiring pycrypto==2.6, yet 2.6.1 is current. can you update this to 2.6 as a min version? I feel it's important that crypto libraries are always allowed to be up to date.

**Comment by jdunck** [comment]
Justin, in #69, I've changed the reqs to allow floating through the 2.6.x line.  I agree crypto should be latest, but also we need to test new, possibly-incompatible versions.  Do you agree with this balance, or do you feel strongly that the version should be unpinned, risking future failure with incompatible versions?

**Comment by justmobilize** [comment]
Jeremy, I think that works great. I trust that revisions don't add breaking changes, but know that major and minor might. Thanks for your quick reply!

-Justin

-----Original Message-----
