### ISSUE TITLE
Expose actors for the funnel functionality

### ISSUE THREAD

**Issue by hex337** [keenlabs/KeenClient-Python#68]
Right now you can't get he full return for a funnel query (no actor ids).

**Comment by hex337** [comment]
This was an issue in the Keen gem as well, which got fixed here: 

[https://github.com/keenlabs/keen-gem/commit/7b57308182c69469093314d1b786a2b4a7a3c383](https://github.com/keenlabs/keen-gem/commit/7b57308182c69469093314d1b786a2b4a7a3c383)

**Comment by tushdante** [comment]
Would an appropriate way to fix this just add an extra param to the function? Something like `:all_keys` referenced in the commit? If its set we return the entire response, if not just the "result" key

**Comment by stroud109** [comment]
Yeah, sounds good. I think following the example set in the Keen gem makes sense in this case.

**Comment by stroud109** [comment]
Closing this since we now have an "all_keys" param #70
