### ISSUE TITLE
Add requests SSL packages to README

### ISSUE THREAD

**Issue by marshyski** [keenlabs/KeenClient-Python#74]
In order for keen client to run for me, I had to install extra requests packages:

pyasn1
ndg-httpsclient
pyOpenSSL

**Comment by stroud109** [comment]
Hey @marshyski, thanks for posting this issue! I haven't encountered this one before. Any chance you could give me a bit more info? Was your version of python compiled with SSL?

**Comment by marshyski** [comment]
@stroud109 Are you calling me a liar?  JK ^_^

Fedora 20, Digital Ocean, Python 2.7.5, Python Built with SSL = yes

http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

**Comment by stroud109** [comment]
@marshyski Thanks so much for the added context! I can see now that you're telling the truth :wink: 

It's helpful to know that this is an issue that applies to python < 2.7.9. I'll update the README with this info. If you think this issue requires a different solution, pull requests are gladly accepted.

**Comment by stroud109** [comment]
Added a comment in the Installation section in 425f5b0
