### ISSUE TITLE
Setting custom timestamp breaks Data Enrichment Addons

### ISSUE THREAD

**Issue by PeterNachbaur** [keenlabs/KeenClient-Python#76]
The SDK overrides the entire "keen" dict when adding in a custom client-defined keen.timestamp. This removes any user supplied Data Enrichment addons, which use the "keen" dict.

https://github.com/keenlabs/KeenClient-Python/blob/master/keen/client.py#L40
https://keen.io/docs/data-collection/

Fix should add the custom timestamp to the "keen" dict if it exists, instead of overriding it. 

Shoutout to @chethan2k5 for helping spot this issue!

**Comment by stroud109** [comment]
This issue was fixed in #77
