### ISSUE TITLE
Import error issue in Python 3.5

### ISSUE THREAD

**Issue by anmolonruby** [keenlabs/KeenClient-Python#88]
I am trying to run the basic example of add_client in your README, I am getting the following error:

`from keen.client import KeenClient
ImportError: No module named 'keen.client'; 'keen' is not a package`

I have already ran `pip3 install keen`. I have Keen version 0.3.20

**Comment by stroud109** [comment]
Hi there, sorry that you're having trouble getting set up :( This client is not currently supported in python 3.5 -- we do support 2.6, 2.7, 3.2, 3.3 and 3.4.

**Comment by ReedJessen** [comment]
Hi stroud109,  

Does you team have thoughts about making a Python 3.5 support version of the client?  It would be really helpful for our team.

**Comment by stroud109** [comment]
Hi @ReedJessen and @anmolonruby, I just added support for python 3.5 in #92. Cheers!
