### ISSUE TITLE
New projects have 64-byte master keys, pycrypto supports only 16/24/32-byte AES

### ISSUE THREAD

**Issue by kennygoff** [keenlabs/KeenClient-Python#90]
Generating scoped keys is breaking on newer projects, as the master keys are now 64-byte. They seemed to have changed from 32-byte keys in the past few months. I created a project a month or two ago that has a 32-byte key, and year+ old projects have 32-byte keys. Only the newer one from a week or two ago has 64-byte.

``` python
scoped_key = scoped_keys.encrypt(master_key, {
  "allowed_operations": ["read"],
  "filters": filters
})
```

Exception being thrown:
`ValueError: AES key must be either 16, 24, or 32 bytes long` from pycrypto.

My `keen` module is the lastest `0.3.20`, and `pycrypto` is the latest `2.6.1`.

**Comment by stroud109** [comment]
Hi Kenny, sorry that you're experiencing this issue :( I'll dig into it soon and let you know when there's a fix.

**Comment by stroud109** [comment]
Hey @kennygoff, let me know if the latest version of the SDK works for you!

**Comment by kennygoff** [comment]
Yep, works perfectly! Thanks @stroud109 and @dkador.

**Comment by stroud109** [comment]
Glad to hear it @kennygoff! Thanks for letting us know :)
